version: "3.8"
services:
    bot:
        profiles: ["cli-only"]
        build:
            context: src/
        volumes:
            - ./src/:/app
        env_file: .env

    qdrant:
        image: qdrant/qdrant
        ports:
        - "6333:6333"
        volumes:
        - ./qdrant_storage:/qdrant/storage