version: "3.8"
services:
    bot:
        build:
            context: src/
            dockerfile: Dockerfile.bot
        volumes:
            - ./src/:/app:ro
        env_file: .env
    qdrant:
        image: qdrant/qdrant
        ports:
        - "6333:6333"
        volumes:
        - ./qdrant_storage:/qdrant/storage
        
    dff:
        profiles: ["cli-only"]
        build:
            context: src/
            dockerfile: Dockerfile.dff
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
